// Common
export const UPDATE_ERROR = "UPDATE_ERROR_ADMIN";
export const START_FETCHING = "START_FETCHING_ADMIN";

export const UPDATE_SITE_INDEX = "UPDATE_SITE_INDEX";

export const UPDATE_ADMIN_PRODUCTS_REQUEST = "UPDATE_ADMIN_PRODUCTS_REQUEST";
export const UPDATE_ADMIN_PRODUCTS = "UPDATE_ADMIN_PRODUCTS";
export const UPDATE_ONLY_ADMIN_PRODUCTS = "UPDATE_ONLY_ADMIN_PRODUCTS";

export const UPDATE_ADMIN_ORDERS_REQUEST = "UPDATE_ADMIN_ORDERS_REQUEST";
export const UPDATE_ADMIN_ORDERS = "UPDATE_ADMIN_ORDERS";
export const UPDATE_ONLY_ADMIN_ORDERS = "UPDATE_ONLY_ADMIN_ORDERS";
