// Common
export const UPDATE_ERROR = "UPDATE_ERROR";
export const START_FETCHING = "START_FETCHING";

// Fetch User Data
export const FETCH_USER_DATA = "FETCH_USER_DATA";

// Update User Token
export const UPDATE_USER_TOKEN_REQUEST = "UPDATE_USER_TOKEN_REQUEST";
export const UPDATE_USER_TOKEN = "UPDATE_USER_TOKEN";

// Get Current Profile
export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_ERROR = "USER_PROFILE_ERROR";

// Fetch Favourite sellers
export const FAVOURITE_SELLERS_REQUEST = "FAVOURITE_SELLERS_REQUEST";
export const FAVOURITE_SELLERS_SUCCESS = "FAVOURITE_SELLERS_SUCCESS";

// Fetch Favourite products
export const FAVOURITE_PRODUCTS_REQUEST = "FAVOURITE_PRODUCTS_REQUEST";
export const FAVOURITE_PRODUCTS_SUCCESS = "FAVOURITE_PRODUCTS_SUCCESS";

// Update Location
export const USER_UPDATE_LOCATION = "USER_UPDATE_LOCATION";

// Update Addresses
export const USER_ADDRESSES_REQUEST = "USER_ADDRESSES_REQUEST";
export const USER_ADDRESSES_SUCCESS = "USER_ADDRESSES_SUCCESS";

// Update Payments
export const USER_PAYMENT_REQUEST = "USER_PAYMENT_REQUEST";
export const USER_PAYMENT_SUCCESS = "USER_PAYMENT_SUCCESS";

// Update Active Orders
export const USER_ACTIVE_ORDERS_REQUEST = "USER_ACTIVE_ORDERS_REQUEST";
export const UPDATE_USER_ACTIVE_ORDERS = "UPDATE_USER_ACTIVE_ORDERS";

// Update User Orders
export const USER_ORDERS_REQUEST = "USER_ORDERS_REQUEST";
export const UPDATE_USER_ORDERS = "UPDATE_USER_ORDERS";

// Categories
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";

// Update Cart Badge Status
export const UPDATE_CART_BADGE_STATUS = "UPDATE_CART_BADGE_STATUS";

// Logout
export const USER_LOG_OUT = "USER_LOG_OUT";
