name: Deploy Development

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16.X
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_REACT_APP_GOOGLE: ${{ secrets.REACT_APP_GOOGLE_DEV }}
        envkey_REACT_APP_STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY_DEV }}
        envkey_REACT_APP_SENTRY_DSN: ${{ secrets.SENTRY_DSN_DEV }}
        envkey_REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL_DEV }}
        file_name: .env
    - name: Yarn Install
      run: |
        yarn install
    - name: Development Build
      run: |
        yarn build dev
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: "staging.properorder.ie"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "eu-west-1"
        SOURCE_DIR: "build"